language: cpp

dist: trusty

sudo: false

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      # For newer gcc version
      - ubuntu-toolchain-r-test
      # For newer clang version
      - llvm-toolchain-trusty
    packages:
      - g++-4.9
      - clang-3.6
      - libopus-dev
      - libssl-dev
      - libprotobuf-dev
      - libmpdclient-dev
      - protobuf-compiler

before_script:
  - ./autogen.sh
  - if [ "$CXX" = "g++" ]; then export CXX='g++-4.9 -std=c++1y'; fi
  - if [ "$CXX" = "clang++" ]; then export CXX='clang++-3.6 -std=c++1y'; fi
  - echo "$CXX"
  - $CXX --version
