language: cpp

dist: trusty

sudo: false

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libopus-dev
      - libssl-dev
      - libprotobuf-dev
      - libmpdclient-dev
      - protobuf-compiler

before_script:
  - ./autogen.sh

script:
  - CXX='g++ -std=c++1y' ./configure --without-libuv
  - make
  - make test
