language: cpp

sudo: false

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libopus-dev
      - libssl-dev
      - libprotobuf-dev
      - libmpdclient-dev
      - protobuf-compiler

before_script: ./autogen.sh
