language: cpp

dist: trusty

sudo: false

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - gcc-4.8
      - clang-3.5
      - libopus-dev
      - libssl-dev
      - libprotobuf-dev
      - libmpdclient-dev
      - protobuf-compiler

before_script:
  - ./autogen.sh
  - if [ "$CXX" = "g++" ]; then export CXX='g++-4.8 -std=c++1y'
  - if [ "$CXX" = "clang++" ]; then export CXX='clang++-3.5 -std=c++1y'
