platform: x64

environment:
  matrix:
#    - compiler: msvc
#      ARCH: amd64
#      CFG: release
#    - compiler: msvc
#      ARCH: x86
#      CFG: release
#    - compiler: msvc
#      ARCH: amd64
#      CFG: debug
#    - compiler: msvc
#      ARCH: x86
#      CFG: debug
    - compiler: msys2
      # Warning: MSYSTEM is case sensitive (must be upper case!)
      MSYSTEM: MINGW64
      MSYSTEM_SUBDIR: mingw64
#    - compiler: msys2
#      # Warning: MSYSTEM is case sensitive (must be upper case!)
#      MSYSTEM: MINGW32
#      MSYSTEM_SUBDIR: mingw32

build_script:
  - 'if "%compiler%"=="msys2" set PATH=C:\msys64\%MSYSTEM_SUBDIR%\bin;C:\msys64\usr\bin;C:\msys64;%PATH%'
  - 'if "%compiler%"=="msys2" bash --login -c "pacman --noconfirm -S mingw-w64-$MSYSTEM_CARCH-{opus,protobuf}"'
  - 'if "%compiler%"=="msys2" bash --login -c "echo $PKG_CONFIG_PATH"'
  - 'if "%compiler%"=="msys2" bash --login -c "cd $APPVEYOR_BUILD_FOLDER; ./autogen.sh; ./configure --build=$MSYSTEM_CHOST --host=$MSYSTEM_CHOST --prefix=$MSYSTEM_PREFIX; make; make check"'

# disable automatic tests
test: off
